apiVersion: v2
name: forgejo
description: Self-hosted Git service (formerly Gitea)
type: application
version: 0.0.1
appVersion: "15.0.7"

dependencies:
  - name: forgejo
    repository: oci://code.forgejo.org/forgejo-helm
    version: 17.1.5
