apiVersion: v2
name: forgejo
description: Self-hosted Git service (formerly Gitea)
type: application
version: 0.0.1
appVersion: "16.0.1"

dependencies:
  - name: forgejo
    repository: oci://codeberg.org/forgejo-contrib/forgejo
    version: 16.0.1
