apiVersion: v2
name: forgejo
description: Self-hosted Git service (formerly Gitea)
type: application
version: 0.0.1
appVersion: "10.0.0"

dependencies:
  - name: forgejo
    repository: oci://codeberg.org/forgejo/forgejo
    version: 10.0.1
