apiVersion: v2
name: authentik-remote-cluster
description: Authentik outpost for remote clusters - proxies auth requests to authentik server on infra cluster
type: application

version: 0.1.0

appVersion: "2026.2.3"

dependencies:
  - name: authentik-remote-cluster
    repository: https://charts.goauthentik.io
    version: 2.1.0
