apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebula-sync-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nebula-sync-secret
  data:
  - secretKey: primary
    remoteRef:
      key: kv/pihole
      property: primary
  - secretKey: replicas
    remoteRef:
      key: kv/pihole
      property: replicas
