authentik:
  global:
    security:
      allowInsecureImages: true
    env:
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-pass
            key: dbpass
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: db-pass
            key: secretkey
    revisionHistoryLimit: 1
    image:
      repository: registry.durp.info/goauthentik/server
      pullPolicy: Always
  authentik:
    outposts:
      container_image_base: registry.durp.info/goauthentik/%(type)s:%(version)s
    postgresql:
      host: "{{ .Release.Name }}-postgresql-hl"
      name: "authentik"
      user: "authentik"
      port: 5432
  server:
    name: server
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
  worker:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
  postgresql:
    enabled: true
    image:
      registry: registry.durp.info
      repository: library/postgres
      pullPolicy: Always
    postgresqlUsername: "authentik"
    postgresqlDatabase: "authentik"
    existingSecret: db-pass
    persistence:
      enabled: true
      storageClass: longhorn
      size: 16Gi
      accessModes:
        - ReadWriteMany
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi
    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 6
  redis:
    enabled: true
    master:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    image:
      registry: registry.durp.info
      repository: library/redis
      pullPolicy: Always
    architecture: standalone
    auth:
      enabled: false
