external-dns:
  global:
    imageRegistry: harbor.durp.info/dockerhub
    security:
      allowInsecureImages: true

  image:
    repository: bitnamilegacy/external-dns
    pullPolicy: Always

  txtPrefix: "dmz-"

  sources:
    - service
    
  provider: cloudflare
  cloudflare:
    secretName : "external-dns"
    proxied: false

  policy: sync
