apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubero-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kubero-secrets
    creationPolicy: Owner
  data:
    - secretKey: KUBERO_WEBHOOK_SECRET
      remoteRef:
        key: kubero
        property: webhook_secret
    - secretKey: KUBERO_ADMIN_USERNAME
      remoteRef:
        key: kubero
        property: admin_username
    - secretKey: KUBERO_ADMIN_PASSWORD
      remoteRef:
        key: kubero
        property: admin_password
    - secretKey: KUBERO_SESSION_KEY
      remoteRef:
        key: kubero
        property: session_key