apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclarity-postgres-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openclarity-postgres-secret
  data:
    - secretKey: username
      remoteRef:
        key: kv/openclarity/postgres
        property: username
    - secretKey: postgres-password
      remoteRef:
        key: kv/openclarity/postgres
        property: password
    - secretKey: password
      remoteRef:
        key: kv/openclarity/postgres
        property: password
    - secretKey: database
      remoteRef:
        key: kv/openclarity/postgres
        property: database
