cloudnative-pg:
  # Operator config
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Always pull the operator image to pick up new point releases
  image:
    pullPolicy: Always

  # Generate certificates via cert-manager (we have it)
  certManager:
    enabled: true

  # Expose operator metrics for Prometheus
  metrics:
    enabled: true
