apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.infra.durp.info"
      path: "secret"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: ca-pemstore
        key: vault.pem
        namespace: external-secrets
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets