apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |-
    use_default_settings: true
    search:
      formats:
        - html
        - json
    engines:
      # Disabled engines - failing with 403 on init from cluster egress IP
      - name: wikidata
        disabled: true
      - name: ahmia
        disabled: true
      - name: torch
        disabled: true