apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ak-outpost-dmz-token
  namespace: authentik
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: ak-outpost-dmz-token
  data:
    - secretKey: AUTHENTIK_TOKEN
      remoteRef:
        key: kv/authentik/dmz-outpost
        property: AUTHENTIK_TOKEN
