cert-manager:
  imageRegistry: harbor.durp.info/quay
  crds:
    enabled: true
  image:
    repository: ""
    pullPolicy: Always
  replicaCount: 3
  extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
    - --dns01-recursive-nameservers-only
  podDnsPolicy: None
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
      - "1.0.0.1"
  webhook:
    image:
      repository: ""
      pullPolicy: Always
  cainjector:
    image:
      repository: ""
      pullPolicy: Always

  hostAliases:
  - ip: 192.168.12.141
    hostnames:
    - vault.infra.durp.info
